[pytest]
asyncio_mode = auto
testpaths = tests
# Убирает варнинг про asyncio_default_fixture_loop_scope:
asyncio_default_fixture_loop_scope = function

# Настройка фильтрации остальных предупреждений:
filterwarnings =
    ignore::DeprecationWarning:passlib.*
    ignore::DeprecationWarning:web3.*
    ignore::DeprecationWarning:websockets.*
    ignore::DeprecationWarning:jose.*
